### ISSUE TITLE
Feature request: more builtin mp_set_* functions

### ISSUE THREAD

**Issue by HDembinski** [boostorg/mp11#25]
Mp11 is great, thank you!

Some additional set operations would be nice:
- `mp_set_union<L1, L2, ..., Ln>` computes the union of n sets
- `mp_set_intersection<L1, L2, ..., Ln>` computes the intersection of n sets
- `mp_set_difference<L1, L2>` computes the differences of two sets

`mp_set_union` is very similar to `mp_set_push_back`, but the latter accepts Ts, not Ls. `mp_set_union` is probably simple to implement with the existing functions, but since these are common set operations, it would be nice to have these operations already defined in the library.

**Comment by kedarbhat** [comment]
I wrote mp_set_union today (as a programming exercise). I’ll write intersection/difference tomorrow and submit for Peter Dimov to review (if he wants these operations in project).
