### ISSUE TITLE
consider adding the detection stuff to mp11?

### ISSUE THREAD

**Issue by hhggit** [boostorg/mp11#30]
The detection idiom is quite helpful in writing SFINAE. Would you @pdimov  consider adding them to mp11? 
https://en.cppreference.com/w/cpp/experimental/is_detected
``` cpp
template <template <class...> class Op, class... Args>
using is_detected = mp_valid<Op, Args...>;

template <class Default, template <class...> class Op, class... Args>
using detected_or_t =
    mp_eval_if<mp_not<mp_valid<Op, Args...>>, Default, Op, Args...>;

template <template <class...> class Op, class... Args>
using detected_t = detected_or_t<detail::mp_no_type, Op, Args...>;

template <class Expected, template <class...> class Op, class... Args>
using is_detected_exact = std::is_same<Expected, detected_t<Op, Args...>>;

template <class To, template <class...> class Op, class... Args>
using is_detected_convertible =
    std::is_convertible<detected_t<Op, Args...>, To>;
```

**Comment by hhggit** [comment]
I didn't get the changes in boost_typetraits, sorry for bothering.

**Comment by pdimov** [comment]
I've actually thought about adding mp_valid_or<D, F, T...> (the equivalent of detected_or_t), and mp_valid_and_true<F, T...> which gives mp_true if F<T...> is valid and true, and mp_false otherwise. But given the overlap, I'm not sure we need them.

Can you outline a few recent uses you had for these traits?

**Comment by hhggit** [comment]
I mainly use the detection idiom for:
 1. dectecting nested type like alloctor_type, value_type,
 2. dectecting member function or ADL funtion t.data() or data(t).

Recently I wrote a `chunk_holder` to hold any continuous chunk buffer such as `vector` or `string`.
The detection idiom helped a lot in getting the chunk buffer's memory range.
