### ISSUE TITLE
mp_with_index: error in example in documentation

### ISSUE THREAD

**Issue by tobias-loew** [boostorg/mp11#36]
Hi,
in the example to mp_with_index the entity "I" is a variable (not a type) and a "decltype" has to be added.

std::cout << std::get<decltype(I)>( v ) << std::endl;

(with C++20 we will be able to deduce the type directly in the lambda)
thanks for the great library!

**Comment by pdimov** [comment]
The example works as written for me. `I` is `integral_constant`, which has a `constexpr` conversion to its value type, the value of which is used as the template parameter of `get` (the overload taking an index.)

**Comment by tobias-loew** [comment]
You're right. Sorry for the effort. It now also works for me. 
But IMHO the comment "I is mp_size_t<v.index()> here" could be a bit more precise as "I is of type mp_size_t<v.index()> here".
