### ISSUE TITLE
Proposal: Jump table based O(1) mp_with_index

### ISSUE THREAD

**Issue by lennoxho** [boostorg/mp11#38]
Example implementation:
https://godbolt.org/z/AFZjKd

This would be very useful for boost::variant:
https://godbolt.org/z/sliiP3

**Comment by pdimov** [comment]
https://godbolt.org/z/NgHa1o

**Comment by pdimov** [comment]
Compilers are pretty good at optimizing `switch` nowadays, turning it into a (jump) table, if needed: https://godbolt.org/z/2HScsH https://godbolt.org/z/9WStAe

**Comment by pdimov** [comment]
And here's the variant example: https://godbolt.org/z/IifWbw

**Comment by lennoxho** [comment]
Thanks for taking a look.
I agree that compilers are pretty good at identifying opportunities to create jump tables.

However, my proposal was motivated by the observation that in less-than-trivial cases, the compiler more often than not is not able to make that deduction.

For example:
https://godbolt.org/z/FSHzKF

This is probably an extreme example, but I think it perfectly shows how the compiler can fail to see the obvious:
https://godbolt.org/z/lyPgKb

**Comment by pdimov** [comment]
Manually creating the jump table is not a guaranteed win. In many practical scenarios the compiler can optimize the switch better. I've chosen to use a switch. The gcc team has proven responsive to bug reports about switch not generating optimal code, f.ex. https://gcc.gnu.org/bugzilla/show_bug.cgi?id=87205

**Comment by lennoxho** [comment]
I can see how it makes sense to delegate the jump table problem to the compiler writers.

Do you think there's still any value in providing an alternative function to mp_with_index which manually creates a jump table? It may be useful for developers who want that guarantee - "O(1)" instead of "O(n) or O(1), really depends on your compiler".

Feel free to close the issue if you think we shouldn't pursue that idea.
