### ISSUE TITLE
Compile error when using MP11 with GMP multiprecision

### ISSUE THREAD

**Issue by dancooke** [boostorg/mp11#41]
See [this issue](https://github.com/boostorg/log/issues/90), in particular the [reduced test case](https://github.com/boostorg/log/issues/90#issuecomment-529955252).

**Comment by dancooke** [comment]
Issue also [reported](https://github.com/boostorg/multiprecision/issues/158) on multiprecision.

**Comment by pdimov** [comment]
Looks like a Clang parser bug:

```
template<class L> struct mp_size;

struct __mpf_struct
{
    int _mp_size;
};

struct X
{
    __mpf_struct m_data[1];
    
    void f()
    {
        if(((m_data)->_mp_size < 0 ? -1: (m_data)->_mp_size > 0) == 0)
        {
        }
    }
};
```

Not sure what we can do about it.

**Comment by dancooke** [comment]
Thanks. [Reported](https://bugs.llvm.org/show_bug.cgi?id=43266).
