### ISSUE TITLE
IAR compiler does not define identifier `__builtin_unreachable`

### ISSUE THREAD

**Issue by jeremy-murphy** [boostorg/mp11#46]
When I tried to compile Variant2 1.72.0, I hit this error with IAR compiler for Arm 8.30.2:

`Error[Pe020]: identifier "__builtin_unreachable" is undefined C:\Src\boost_1_72_0\boost\mp11\detail\mp_with_index.hpp 83 `

and on all the other lines where `__builtin_unreachable` is used.

**Comment by pdimov** [comment]
Should be fixed on develop with https://github.com/boostorg/mp11/commit/1f634c7071d38aff82578efa745a65e54dca4fb3.

**Comment by jeremy-murphy** [comment]
Thanks!
