### ISSUE TITLE
Interest in tuple_transform?

### ISSUE THREAD

**Issue by HDembinski** [boostorg/mp11#49]
I would like to contribute a tuple_transform. It accepts a tuple and a callable and constructs a new tuple from the callable applied to each element of the tuple. It works like `construct_from_tuple`, but transforms each element (value and/or type).

**Comment by pdimov** [comment]
Yes please. This is something I intended to add.

**Comment by HDembinski** [comment]
Ok, I am on it.

**Comment by HDembinski** [comment]
You are probably already aware of this: straight-forward implementation has the caveat that the evaluation order of the functor on the arguments is platform-dependent. I noticed that it changed between gcc versions, for instance. I don't have a solution for that.

The trick of using an initializer_list does not work, because we don't have a collection of identical types.

**Comment by HDembinski** [comment]
See #50 for a draft of the feature
