### ISSUE TITLE
feature request: mp_split

### ISSUE THREAD

**Issue by u3shit** [boostorg/mp11#59]
I'm trying to port some software from [brigand](https://github.com/edouarda/brigand) (which sadly doesn't look maintained anymore) to boost mp11 and this is the only function I need that doesn't have an equivalent in mp11.

`mp_split<L<T1_1, T1_2, ..., T1_n, S, T2_1, ..., T2_m, S, ...>, S>` should be equal to `L<L<T1_1, T1_2, ..., T1_n>, L<T2_1, T2_2, ..., T2_m>, ...>>`

Here's the implementation in brigand: https://github.com/edouarda/brigand/blob/master/include/brigand/algorithms/split.hpp

**Comment by pdimov** [comment]
This looks fairly trivial, except for the case where S is not present in L at all.

**Comment by u3shit** [comment]
Brigand just returns `L<L<T...>>` in that case, which looks reasonable for me.
Actually a more interesting case is when L starts or ends with S and duplicate S. Now in brigand, `split<L<S, T...>, S>` is `L<L<T...>>`, and `split<L<T1, S, S, T2>, S>` is `L<L<T1>, L<T2>>`, but it might make more sense to leave empy `L<>`s in the output. So `split<L<S, T...>, S>` could be `L<L<>, L<T...>>` and `split<L<T1, S, S, T2>, S>` is `L<L<T1>, L<>, L<T2>>`. One advantage of this latter method that you can write a `join` that unambigously reconstructs the original list. (Actually I realized that my code already had a join implementation because that's missing even from brigand.)

Now in my intended use case, `split<L<T...>, S>` should be `L<L<T...>>` when there is no S in T. The other cases, I don't care about them (they shouldn't happen in my case)

**Comment by pdimov** [comment]
Yeah, mp_join would be a natural companion. There's one more corner case: `mp_split<L<>, S>`, which can equally well be `L<>` or `L<L<>>`.

**Comment by u3shit** [comment]
Brigand does `L<>` in this case, but yeah, both of them is fine.

**Comment by pdimov** [comment]
Implemented mp_split, mp_join on develop; since 1.76 is in beta, they will go into 1.77.

**Comment by u3shit** [comment]
Checked it out, looks OK. :+1:

>will go into 1.77

It looks like it'll take some time before I can remove my current workaround. Thanks anyway.
