### ISSUE TITLE
New warning for mp_count in gcc-10 with cxxstd=20

### ISSUE THREAD

**Issue by HDembinski** [boostorg/mp11#60]
```
../../boost/mp11/detail/mp_count.hpp:54:31: error: comparison of unsigned expression in ‘< 0’ is always false [-Werror=type-limits]
   54 |     for( std::size_t i = 0; i < sizeof...(T); ++i )
      |                             ~~^~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
```
https://github.com/boostorg/histogram/pull/317/checks?check_run_id=2185335442#step:5:198

**Comment by HDembinski** [comment]
These warnings in constexpr contexts are a bit useless sometimes.

**Comment by pdimov** [comment]
Entirely useless, but what can you do. Thanks. I now need to figure out why I'm not getting this warning on CI (or locally).

I was being too clever by adding a `false` in front to avoid specializing for the zero case, but apparently this trick won't work.

**Comment by pdimov** [comment]
Ah, I'm missing <warnings>extra. Let's see what else will break.

**Comment by pdimov** [comment]
Should be fixed now.
