### ISSUE TITLE
msvc-14.3 reports internal compiler error in boost/mp11/algorithm.hpp(370)

### ISSUE THREAD

**Issue by HDembinski** [boostorg/mp11#74]
I made a trivial change to the histogram develop branch today and started seeing these failures:

https://ci.appveyor.com/project/HDembinski/histogram-d5g5k/builds/44806268#L931

This is very puzzling and I don't how to fix this. Peter, can you help me, please?

The failures cannot originate from a change in boost histogram. The last time I tested the develop branch was at July 28th, where the appveyor tests ran through. 
https://ci.appveyor.com/project/HDembinski/histogram-d5g5k/builds/44309070#L900

I did some more testing in a virtual machine with msvc-14.3 installed and found that I am now getting this error even when I go back to boost-1.79.0 and boost-1.78.0 (histogram, mp11, everything). It is always complaining about that line.

So given all that evidence, I guess msvc-14.3 got a minor version update and that is causing the internal compiler error?

**Comment by pdimov** [comment]
This must be it. I'm not getting the error from the mp11 test suite, and Histogram is probably not part of MS's test suite for the new compiler releases. It would be worth reporting this to them.

**Comment by HDembinski** [comment]
Ok, I reported it to MS.

**Comment by pdimov** [comment]
Link please?

**Comment by HDembinski** [comment]
Not sure whether this is publicly visible, but here you go: https://developercommunity.visualstudio.com/t/fatal-error-C1001-in-Boost-Histogram/10151825

**Comment by pdimov** [comment]
It is, thanks. They seem to want more info in order to reproduce.

**Comment by HDembinski** [comment]
Yes, I can see that. This is the shortest reproducer I managed to create so far https://godbolt.org/z/jn77avxs1

**Comment by pdimov** [comment]
Closed as fixed in VS 17.4 (MSVC 19.34) so we can close this as well, I suppose?
