### ISSUE TITLE
Standalone build of mp11 with CMake 3.25.1 does not build tests

### ISSUE THREAD

**Issue by ilyapopov** [boostorg/mp11#81]
I tried the following:

```
git clone git@github.com:ilyapopov/mp11.git
cd mp11
cmake -B build -DBUILD_TESTING=ON
make -C build
make -C build test
```

and got messages that test executables are not found. I have printed the value of `BUILD_TESTING` just before https://github.com/boostorg/mp11/blob/3e84aef18e2083538bdbb748d63daf8aa7392c7d/CMakeLists.txt#L62 and found it empty. It looks like the line https://github.com/boostorg/mp11/blob/3e84aef18e2083538bdbb748d63daf8aa7392c7d/CMakeLists.txt#L49 does not do what it supposed to.

**Comment by ilyapopov** [comment]
Looks like it is related to https://cmake.org/cmake/help/latest/policy/CMP0077.html#policy:CMP0077 , more soecifically:

> In CMake 3.13 and above the [option()](https://cmake.org/cmake/help/latest/command/option.html#command:option) command prefers to do nothing when a normal variable of the given name already exists. It does not create or update a cache entry or remove the normal variable. The new behavior is consistent between the first and later runs in a build tree.

**Comment by pdimov** [comment]
I believe the reason is that you need to build the `tests` target first instead of the default one.

**Comment by ilyapopov** [comment]
Oh, yes, that works, sorry for the false alarm.
